// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxkh4I_JuT8MxkiHTD554_DdiJObo7aSw',
    appId: '1:796302433608:web:7053113be8d6c8709aa77d',
    messagingSenderId: '796302433608',
    projectId: 'crudtest-2aedc',
    authDomain: 'crudtest-2aedc.firebaseapp.com',
    storageBucket: 'crudtest-2aedc.appspot.com',
    measurementId: 'G-5KVE6V1DDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlmRl25h-nGwfDd9Ii2kSyq89IqNxwKWA',
    appId: '1:796302433608:android:6ceb237381e7d6d29aa77d',
    messagingSenderId: '796302433608',
    projectId: 'crudtest-2aedc',
    storageBucket: 'crudtest-2aedc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvm0i-Vs6RIUiqzE_am6ftbYoqlUKtuk8',
    appId: '1:796302433608:ios:d0ba7129d67a1ade9aa77d',
    messagingSenderId: '796302433608',
    projectId: 'crudtest-2aedc',
    storageBucket: 'crudtest-2aedc.appspot.com',
    iosBundleId: 'com.example.flutterquizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvm0i-Vs6RIUiqzE_am6ftbYoqlUKtuk8',
    appId: '1:796302433608:ios:2c05825142419b0c9aa77d',
    messagingSenderId: '796302433608',
    projectId: 'crudtest-2aedc',
    storageBucket: 'crudtest-2aedc.appspot.com',
    iosBundleId: 'com.example.flutterquizapp.RunnerTests',
  );
}
